### ISSUE TITLE
viewer example

### ISSUE THREAD

**Issue by lazydino** [Herbal3d/basil#2]
Hi,

I noticed that the viewer was used for rendering convoar results  ( https://misterblue.com/oars/ ) Is there an web application example shows me how to do that?  Is basil viewer, or a reference implementation done for threejs/opensim , a gRPC server using protobuf?

**Comment by Misterblue** [comment]
been a while... This is not yet a freely available web example -- I need to get all the permissions and authentication working before letting it loose on the web. That said, the code in the OARs example is an early version that just loaded the target GLTF without using the protocol. A protocol based version will appear sometime in 2020.
