### ISSUE TITLE
Couldn't start the project - missing doc

### ISSUE THREAD

**Issue by themavenhater** [Herbal3d/basil#20]
i tried to start the project, i ran :

**yarn
yarn build
yarn start**

it created a declarations and dist folders. 
i get this error when i run yarn start :

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '/Users/mac/Desktop/basil/Basilts/dist/index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by Misterblue** [comment]
You don't "run" Basil in that manner. Basil is a web page and is loaded and run in a browser. It is not an application you run standalone.
What I do is make the dist/ directory available from a web server and then start the browser at https://mysite.example.com/dist/index.html. The page "index.html" is that entry page you can view at https://basil.bluestuff.org and which logs one into OSGrid and directs the user to the region BasilAlpha.
There is an initial web page of "Entry.html" which has more testing startup things. What happens is that the Entry.html page gathers parameters and builds a parameter string and reloads the page Basil.html with the connection parameters.
If you just start dist/Basil.htim, it will load a test scene in orbit view mode.
Anyway, one doesn't "run" Basil, you view it in a browser.

**Comment by themavenhater** [comment]
Thanks for the explanation
